from Mahasiswa import Mahasiswa
import os

def main():
    try:
        data = Mahasiswa()
        name = input ('Nama Mahasiswa\t : ')
        data.setname(name)
        nim = int(input ('NIM Mahasiswa\t : '))
        data.setnim(nim)
        smstr = int(input ('Semester Saat ini : '))
        if (smstr == 2):
            ip1 = float(input('IP Semester 1: '))
            data.setip1(ip1)
        elif(smstr == 3):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            data.setip1(ip1)
            data.setip2(ip2)
        elif(smstr == 4):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
        elif(smstr == 5):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            ip4 = float(input('IP Semester 4: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
            data.setip4(ip4)
        elif(smstr == 6):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            ip4 = float(input('IP Semester 4: '))
            ip5 = float(input('IP Semester 5: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
            data.setip4(ip4)
            data.setip5(ip5)
        elif(smstr == 7):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            ip4 = float(input('IP Semester 4: '))
            ip5 = float(input('IP Semester 5: '))
            ip6 = float(input('IP Semester 6: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
            data.setip4(ip4)
            data.setip5(ip5)
            data.setip6(ip6)
        elif(smstr == 8):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            ip4 = float(input('IP Semester 4: '))
            ip5 = float(input('IP Semester 5: '))
            ip6 = float(input('IP Semester 6: '))
            ip7 = float(input('IP Semester 7: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
            data.setip4(ip4)
            data.setip5(ip5)
            data.setip6(ip6)
            data.setip7(ip7)
        elif(smstr == 9):
            ip1 = float(input('IP Semester 1: '))
            ip2 = float(input('IP Semester 2: '))
            ip3 = float(input('IP Semester 3: '))
            ip4 = float(input('IP Semester 4: '))
            ip5 = float(input('IP Semester 5: '))
            ip6 = float(input('IP Semester 6: '))
            ip7 = float(input('IP Semester 7: '))
            ip8 = float(input('IP Semester 8: '))
            data.setip1(ip1)
            data.setip2(ip2)
            data.setip3(ip3)
            data.setip4(ip4)
            data.setip5(ip5)
            data.setip6(ip6)
            data.setip7(ip7)
            data.setip8(ip8)
        else:
            print('Data yang anda masukan tidak terdeteksi oleh system !!!')
            print('Aplikasi dalam tahap uji coba')
            os._exit(0)

        data.setsmstr(smstr)
        data.setttlip()
        total = data.getttlip()
        data.setipk()
        ipk = data.getipk()
        Vname = data.getname()
        Vnim = data.getnim()
        Vsmstr = data.getsmstr()

        print('\n==============DATA MAHASISWA==============')
        print('Nama\t\t: ', Vname)
        print('NIM\t\t: ', Vnim)
        print('Semester\t: ', Vsmstr)
        print('IP Total\t: ', total)
        print('IPK\t\t: ', ipk)
    except:
        print('Data yang anda masukan salah !!!')
main()